name: run unit tests pf feature branches

on:
  push:
    branches:
      'feature/*'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: run unit test
        run: python -m unittest tests/SumTest.py
