name: nightly build at 11pm

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  nightly_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: run unit test
        run: python3 -m unittest tests/SumTest
